-- postgreSQL
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
	UID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD VARCHAR(60) NOT NULL,
	USERNAME VARCHAR(50) NOT NULL
);

INSERT INTO USERS(EMAIL, PASSWORD, USERNAME) VALUES 
('test@test.com', '123123', 'test');

select * from users;